server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoaoCaboclo/spring-cloud-config-server
          repos:
            staging-properties-repo:
              pattern: config-client/staging
              uri: https://github.com/JoaoCaboclo/spring-cloud-config-server
              search-paths:
                - spring-cloud-config-server-setup/configs-location

            prod-properties-repo:
              pattern: config-client/prod
              uri: https://github.com/JoaoCaboclo/spring-cloud-config-server
              search-paths:
                - spring-cloud-config-server-setup/configs-location/{profile}

            any-properties-repo:
              pattern: config-client*/*
              uri: https://github.com/JoaoCaboclo/spring-cloud-config-server
              search-paths:
                - spring-cloud-config-server-setup/configs-location/{application}/{profile}